index:
  path: /
  controller: App\Controller\AvisosController::index

futbol:
  path: /futbol
  controller: App\Controller\AvisosController::futbol

salir:
  path: /logout
  controller: App\Controller\Back\BackController::salir
